### ISSUE TITLE
Add button to export subscribers to form entries

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#108]
## Description

Insert into widget settings of form entries a button to download a list of subscribers in xls format.

**Comment by igr-santos** [comment]
I need know wich are the columns to know about which info represent.
Insert to label of column fix my problem or can mark wich column i need

**Comment by gabrielrtakeda** [comment]
Yes sure, but the data coming from api isn't still the correct, for now, it coming just mobilizations data. The subscribers list from form entries has come something like dataclip.

`Nome: Lorem, Sobrenome: Ipsum, CIDADE: Outra, CEP: xxxxxxxx, EMAIL: dummy@localhost`

That query need to be included on api and create an endpoint do retrieve the correct data. When it returning the correct data, the information about columns will come together, and we can manipulate it on front to create de .xslx file correctly with data reference column name.

**Comment by gabrielrtakeda** [comment]
The `forceDownloadFile` actions isn't receiving the `filename` param and when we'll make the Excel file on `makeExcelFile` function, we need to export the object values. I'll fix this here.

**Comment by igr-santos** [comment]
I think need to do export of informations by Widget, doesn't by Mobilization, because one mobilization has many FormWidget and each FormWidget has many lines of information

**Comment by gabrielrtakeda** [comment]
Needs to handle the behaviour when detects that browser is Safari, because Safari isn't support `a[download]` attribute yet (check [a[download] attribute](http://caniuse.com/#feat=download) supported browsers). For that, i opened a PR (rndme/download#33)  to make [downloadjs](https://github.com/rndme/download) module accepts an option object and we pass a function in `options.safariCallback()` to overwrite the current behaviour to Safari.

While the PR isn't merged, i'll point the [downloadjs](https://github.com/rndme/download) module dependency on `hub-client` repo to [my forked repository](https://github.com/gabrielrtakeda/download). What do you think?

**Comment by gabrielrtakeda** [comment]
Need to fix "Salvar planilha" button onclick method to avoid mistaken clicks and change button's background color to outlined style.

<img width="785" alt="captura de tela 2016-07-25 as 21 10 07" src="https://cloud.githubusercontent.com/assets/5435389/17121747/35b1e312-52ac-11e6-83fd-ae2b5996d3c1.png">
