### ISSUE TITLE
Planner how components will work following new concepts from default widget

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#126]

**Comment by gabrielrtakeda** [comment]
# Introduction

The Direct Pressure functionality may be something like folder structure and front-end code example below:

## Folder structure

```
app
└───scripts (modules for later)
    ├───Block
    │   │   index.js
    │   │   routes.js
    │   │   ...
    │   │
    │   ├───components
    │   │   │   ConfigMenu.jsx
    │   │   │   Card.jsx
    │   │   │   ...
    │   │
    │   └───pages
    │       │   NewBlank.jsx
    │       │   NewTemplate.jsx
    │       │   ...
    │
    ├───ColorPicker (super independent component)
    ├───Widget
    │   └───modules
    │       └───DirectPressure (by types: [email, phone])
    │           │   index.js
    │           │   routes.js
    │           │   ...
    │           │
    │           ├───components
    │           │   │   DirectPressure.jsx (views: [activist, mobilizer])
    │           │   │   Mail.jsx
    │           │   │   PressedOwner.jsx
    │           │   │   Counter.jsx
    │           │   │   ...
    │           │
    │           └───pages
    │               │   Form.jsx
    │               │   Email.jsx
    │               │   AfterPressure.jsx
    │               │   ...
    │
    └───GovernmentOfficeTarget
        ├───components
        ├───containers
        ├───modules
        └───pages
```

### Block

#### File
- `index.js` is the centralizer of all block module configurations e.g.:

``` javascript
import routes from './routes'
import * as components from './components'
import * as pages from './pages'

export default { routes, components, pages }
```
- `routes.js` is the centralizer of all block module routes e.g.:

``` javascript
import { NewBlank, NewTemplate } from './pages'

const r = (path, component) => <Route path={path} component={component} />
export default [
  r('/mobilizations/:mobilization_id/blocks/new/blank', NewBlank),
  r('/mobilizations/:mobilization_id/blocks/new/template', NewTemplate)
]
```

#### Component
- `ConfigMenu` is to compose config pages header menu.
- `Card` to compose `NewTemplate` page.

#### Page
- `NewBlank` is following as current new block page with a new route as `/mobilizations/:mobilization_id/blocks/new/blank`.
- `NewTemplate` is based on following [InVision/New-Block](https://projects.invisionapp.com/share/BQ7JHD7DJ#/screens/176119368) prototype with route as `/mobilizations/:mobilization_id/blocks/new/template` ***Perhaps another epic story**.

### Widget > DirectPressure

The `DirectPressure` is a submodule of `Widget` because it **is** a widget.

Conceptually, that is the correct place for it. The layout and behaviours is based on following [InVision/PDP-Mobilization](https://projects.invisionapp.com/share/BQ7JHD7DJ#/screens/176128696) prototype.

#### File
- `index.js` and `routes.js` follows the same concept as `Block/index|routes.js` files.

#### Component
- `DirectPressure` is the main component. **Suggestion** - we may define a convention to main components like `main.jsx`
- `Mail` is to compose the `DirectPressure` component. Screenshot:
  <img width="590" alt="captura de tela 2016-07-28 as 14 03 12" src="https://cloud.githubusercontent.com/assets/5435389/17221890/13197d52-54cc-11e6-8c4a-5b6c8b2ad21e.png">
- `PressedOwner` is to compose the `DirectPressure` component. Screenshot:
  <img width="584" alt="captura de tela 2016-07-28 as 14 02 30" src="https://cloud.githubusercontent.com/assets/5435389/17221861/fd8d89c4-54cb-11e6-928e-40ec4402a5b7.png">
- `Counter` is to compose the `DirectPressure` component. Screenshot:
  <img width="308" alt="captura de tela 2016-07-28 as 14 04 02" src="https://cloud.githubusercontent.com/assets/5435389/17221930/3054bc4c-54cc-11e6-9157-e2228f3fe79f.png">

**Question** - How do we should add this to the page? Maybe by editor? Need to understand.

#### Page
- `Form` is based on following [InVision/Edit-Form-PDP-Mobilization](https://projects.invisionapp.com/share/BQ7JHD7DJ#/screens/176129303) prototype.
- `Email` is based on following [InVision/Edit-Email-PDP-Mobilization](https://projects.invisionapp.com/share/BQ7JHD7DJ#/screens/176129657) prototype.
- `AfterPressure` is doesn't have prototype yet, but it may have that option later.

### GovernmentOfficeTarget

Still a little obscure about the scope of who can create/modify new targets and visualization rules.

`GovernmentOfficeTarget` module is based on following [InVision/Edit-PDP-Mobilization](https://projects.invisionapp.com/share/BQ7JHD7DJ#/screens/176129657) prototype.

## Front-end code

``` jsx
<DirectPressure type={'email'} />
```

**Comment by lpirola** [comment]
After pressure widget release , we got a lot of module organization knowledge and some important decisions were made to set current folder structure.
