### ISSUE TITLE
Edit mobilization page rendering when change from one to another

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#408]
# Description
When I try to edit another mobilization after choose a mobilization to edit, the second mobilization that I choosed to edit, does not render. Instead, it renders again the first one that I accessed before.

# Steps to reproduce
1. Access mobilization list page
2. Choose one mobilization to edit
3. Return to the mobilization list page
4. Choose a different mobilization of first one

🐛🐛🐛🐛🐛🐛

**Comment by igr-santos** [comment]
**About this**
The informations about widgets and blocks are loaded by [RedialJS](https://github.com/markdalgleish/redial) and it only make the first fetch in server side, when the component is rendered again, the new fetch is didn't make, because that render is maked by client side.

**A possible solution**

Replace the fetch make by **RedialJS**, only on this component (EditMobilization), by a fetch on `componentDidMount` in component lifecycle and every time that mount this component the fetch will be done. Like this commit https://github.com/nossas/bonde-client/commit/b2ca666255683fa315e7b5426765d46889d6d327

**Comment by gabrielrtakeda** [comment]
@igr-santos Great that you have an idea of whats going on in this bug. I was really confused about this and, sincerely, I was going to debug the state, step by step to analyze where is the bug. I will check this further too, to help in a solution.

**Comment by gabrielrtakeda** [comment]
In the predeploy tests #411, I identified that this same bug occurs when I try to create a template from a mobilization (e.g. http://reboo-staging.org/mobilizations/257/templates/create).
