### ISSUE TITLE
Redirect to Erro Page when Token in cookie is not valid anymore

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#430]

**Comment by gabrielrtakeda** [comment]
@lpirola When do you say **Token**, do you mean the **access-token** of credentials object to access the API?

**Comment by lpirola** [comment]
@gabrielrtakeda yes.

At this momento I didn't test an invalidation of token and tried to access some authenticated page. Must redirect to login or show some error message.

**Comment by gabrielrtakeda** [comment]
Ok I get it, thanks.

**Comment by gabrielrtakeda** [comment]
As @igr-santos mentioned in the slack channel, I will put the auth cookie expirity as the same of API response when login success.

**Comment by igr-santos** [comment]
@gabrielrtakeda you should do same thing in community cookie

**Comment by gabrielrtakeda** [comment]
@igr-santos I thought about it but I realized that the community cookie is not an impediment to application keep running with it and, do not have any security issues like auth cookie that holds credentials to access the API.

I really do not see the need to expire the community cookie data together with auth. Actually may be good to keep the community even the auth cookie is gone because, if the auth cookie is not valid anymore, the user needs to make login again and, after he logged in, the system automatically will identify the community that he accessed before.
