### ISSUE TITLE
Move some community configurations to sidebar when mobilization is not selected

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#489]

**Comment by gabrielrtakeda** [comment]
@lpirola Do I remove the **configurações** link from top of sidebar? Considering that the new **"Informações"** navbar item have the same behaviour to redirect to `community/info` route...

<img width="278" alt="screen shot 2017-03-29 at 2 34 21 pm" src="https://cloud.githubusercontent.com/assets/5435389/24468103/8926190c-148d-11e7-9dba-3d01ff363841.png">

**Comment by gabrielrtakeda** [comment]
I removed the **"Configuracões"** link and change the **"Trocar"** text to **"Trocar de comunidade"** because I felt it got a bit empty.. Follow the screenshot:

<img width="274" alt="screen shot 2017-03-29 at 3 16 04 pm" src="https://cloud.githubusercontent.com/assets/5435389/24469729/e920230c-1492-11e7-8c9a-cb6bc4d531dc.png">
