### ISSUE TITLE
Last Donation not found when editing subscription by user

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#732]

**Comment by gabrielrtakeda** [comment]
I added a workaround for this case but, I think that this error occurs because the API is not returning the same data response object as before... Just a guess.. Because, I get the same user that I have tested before and, it is not returning the last donation card data that was returned before... Maybe a more deep investigation on this issue is a good idea.. But for now, the user can access the page to edit the subscription data and, will give us more time to investigate..

**Comment by gabrielrtakeda** [comment]
I have found the bug on user's last donation card data... Disregard the last comment
